### ISSUE TITLE
Understanding model bridging

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [shcaba/Stock-Assessment-Topics-Forum#1]
At the September PFMC meeting, there were many discussions about how the assessments done in 2023 differed from previous assessments and the majority of people did not understand why.  I think walking through the bridging section, which provides comprehensive information about how the model is changing by adding new data and changing modeling assumptions, in any of the stock assessments would be helpful.  I suspect this section is missed by many people and those who do know of it may not fully understand how to interpret these results.

**Comment by shcaba** [comment]
Terrific suggestion!

**Comment by shcaba** [comment]
Had a great discussion on this 12/13/2024, with more to come!
